### ISSUE TITLE
Username with Space causing issues 

### ISSUE THREAD

**Issue by TrollFarmer2411** [scrutinously/chia-scripts#1]
farmStats.sh doesn't like usernames with space in it.
![1](https://user-images.githubusercontent.com/100010881/173714975-a89ba78a-b2ef-4be6-98bc-9eeba07266c2.png)

**Comment by scrutinously** [comment]
Easy answer is don't use spaces in usernames, but I'll look into it.

**Comment by scrutinously** [comment]
Try this updated script with quotes around the path in the awk commands: https://github.com/scrutinously/chia-scripts/blob/master/farmStats.sh

**Comment by TrollFarmer2411** [comment]
Fixed issue. Can mark as resolved
